### ISSUE TITLE
Numbers on to do list

### ISSUE THREAD

**Issue by veredrec** [FACN3/MHHN#22]
When adding some to do's and then deleting them, the next to do the use adds would get the next number, so the user ends up with one to do which is for example 5 (see screen shot): 
![todo](https://user-images.githubusercontent.com/21221306/32596363-bd2b6360-c53b-11e7-8672-d1dcc38e5a03.png)
Sorry for the silly todo I added... :wink:

**Comment by MarlenAw** [comment]
One solution would be..getting rid of the id  :sweat_smile:
