### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by Amirk390** [FACN3/MHHN#25]
The test coverage doesn't test everything :disappointed: 

![image](https://user-images.githubusercontent.com/24490876/32596763-1d295f50-c53d-11e7-86b5-dbdea9684838.png)

**Comment by MarlenAw** [comment]
Thanks for noticing..just learned something new because of this :D 

Adding this line:

 /* istanbul ignore next */  

On line 65 would solve it. But you only do that if you're sure this line doesn't need any testing

In our case..the test has a bug and we're working on it :open_hands:
